@baseUrl = https://8080-victorkashi-atividadesp-74nnjp4wkdk.ws-us116.gitpod.io
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgTW90b3MiLCJzdWIiOiJ2aWN0b3IiLCJleHAiOjE3MjYwMTM1MjV9.Csw4fYFMS4zcjWpZ7sntwJSDDbKFFAhTkN3rNh2mwYM

###
GET {{baseUrl}}/moto
Authorization: Bearer {{token}}

###
POST {{baseUrl}}/moto
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "marca": "BMW",
    "modelo": "G 310 GS"
}

###
GET {{baseUrl}}/moto/3
Authorization: Bearer {{token}}

###
PUT {{baseUrl}}/moto/3
Content-Type: application/json

{
    "marca": "BMW",
    "modelo": "Fazer 250 TRINCA TRINCA QUADRO"
}

###
DELETE {{baseUrl}}/moto/4